const ROOM_COMMENTS_TO_STATE = 'ROOM_COMMENTS_TO_STATE';
const SET_ROOM_COMMENTS = 'SET-ROOM-COMMENTARIES';
const ADD_LIKE = 'ADD-LIKE';
const REMOVE_LIKE = 'REMOVE-LIKE';

export { SET_ROOM_COMMENTS, ADD_LIKE, REMOVE_LIKE, ROOM_COMMENTS_TO_STATE };
